[package]
name = "raytracing"
version = "0.1.0"
authors = ["bela333 <b3kstudio@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.4"
rand = "0.7.3"
rand_distr = "0.2.2"
rayon = "1.3.0"